title: "Image Processing How-To Guides"
author: "Noreen Walker"
description: "Step-by-step instructions for common image processing tasks" # does this get printed?

#theme: jekyll-theme-minimal
remote_theme: "pmarsceill/just-the-docs"

# for configuration options see: https://pmarsceill.github.io/just-the-docs/docs/configuration/

color_scheme: "light" #"dark"

search_enabled: false #TODO

footer_content: " Copyright &copy; 2020 Scientific Computing Facility, MPI-CBG"

back_to_top: true
back_to_top_text: "Back to top"


#plugins:
#  - jekyll-include-cache