title: "Image Processing How-To Guides"
author: "Noreen Walker"
description: "Step-by-step instructions for common image processing tasks" # does this get printed?

remote_theme: "pmarsceill/just-the-docs" #old :theme: jekyll-theme-minimal

# for configuration options see: https://pmarsceill.github.io/just-the-docs/docs/configuration/

# color_scheme: "light" #"dark"
color_scheme: "customparams" # light (default), dark)

# search box
search_enabled: true 
heading_level: 4 # Split pages into sections that can be searched individually, supports 1-6, default 2

# Footer content
footer_content: " Copyright &copy; 2020 Scientific Computing Facility, MPI-CBG"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View on GitHub."
gh_edit_repository: "https://github.com/walkernoreen/ipfguides" # TODO: update after repo shift
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# back-to-top link
back_to_top: true
back_to_top_text: "Back to top"

